POST http://localhost:3000/auth/checkUserSendOTP
Content-Type: application/json

{
    "email": "gustavomottacardoso1@gmail.com"
}

###

POST http://localhost:3000/auth/checkOTP
Content-Type: application/json

{
    "email": "gustavomottacardoso1@gmail.com",
    "OTP": "7529"
} 

###

POST http://localhost:3000/auth/createUser
Content-Type: application/json

{
    "role": "paciente",
    "userId": "677d85c7ebbe9b584d4a42db",
    "name": "Gustavo Mottaaddfdasddfdddfdddfdffdsdfdff",
    "birthdayDate": "20/12/2003",
    "userSpecialities": "Massoterapia",
    "userServicePreferences": "Pet"
} 
